### ISSUE TITLE
settings written incorrectly in windows

### ISSUE THREAD

**Issue by Avinash-Bhat** [mk-5/fjira#43]
**Desktop (please complete the following information):**
 - OS: Win 10
 - Terminal: Powershell
 - Architecture: x86_64
 - Fjira version: [3fea632](https://github.com/mk-5/fjira/commit/3fea63257491c2b08d0a97c4a843ad2fe51305ec)

**Describe the bug**
while configuring the settings during the first run, there is '\r' character added to the workspace json config

**To Reproduce**
1. Start a fresh workspace on Windows 
2. provide values for username, URL and Token.
3. See error

**Expected behavior**
there shouldn't be a \r in the file `~/.fjira/default.json`

**Additional notes**
Problem starts at [internal/fjira/fjira_install.go#L86](https://github.com/mk-5/fjira/blob/3fea63257491c2b08d0a97c4a843ad2fe51305ec/internal/fjira/fjira_install.go#L86).
Maybe using a cross-platform library like github.com/chzyer/readline could help.

**Comment by mk-5** [comment]
hello @Avinash-Bhat ! thanks for report!

Windows is not supported - for now :) Here is an "work in progress" PR: https://github.com/mk-5/fjira/pull/41
There are couple more problems then problem pointed out by that issue. 

I think I will finalize that windows stuff at beginnig of august or something :)

**Comment by mk-5** [comment]
that should actually fix described issue: https://github.com/mk-5/fjira/pull/41/commits/63f78e46af2d1a3a0ec15f29e49cbfb64b0849a2

**Comment by mk-5** [comment]
I need to fix tests, and windows release will be done / there is a problem with changing home directory to the "temp/test" one.

**Comment by mk-5** [comment]
@Avinash-Bhat latest version has window support - I'm still waiting for chocolatey review so it's available as an executable for now: https://github.com/mk-5/fjira/releases/tag/0.10.0

**Comment by mk-5** [comment]
okay - new version in choco review: https://community.chocolatey.org/packages/fjira/0.11.4

**Comment by mk-5** [comment]
Windows version available in Choco. Just use `choco install fjira`. 

I'm closing that issue now - pls feel free to re-open it (or create a new one) in case of any problems with windows version.
