### ISSUE TITLE
Regression: -p does not work anymore

### ISSUE THREAD

**Issue by jneidel** [mk-5/fjira#83]
Tested on version 1.0.2

**Describe the bug**

The -p flag nor its longform work as expected:

```
Flags:
  -h, --help             help for fjira
  -p, --project string   Open a project directly from CLI
```

**To Reproduce**
```sh
fjira -p any
```

**Expected behavior**

Work as described :)

**Comment by mk-5** [comment]
fixed in 1.0.3
