### ISSUE TITLE
SSL handshake timeout

### ISSUE THREAD

**Issue by izifortune** [mk-5/fjira#85]
**Desktop (please complete the following information):**
 - OS: MacOS Ventura
 - Terminal: Alacritty
 - Architecture: x86
 - Fjira version: 1.0.3

**Describe the bug**
Custom SSL certificates are not read while connecting to jira leading to an SSL timeout error.
Environment variables such as SSL_CERT_FILE are correctly setup.

**Comment by mk-5** [comment]
@izifortune thanks for reporting!

`http.DefaultTransport` is in use - https://github.com/mk-5/fjira/blob/a840c9d2d7614d1b416e7cf7fafcd9db51d21246/internal/jira/jira.go#L214C2-L214C2

I'm surprise that it's not taking `SSL_CERT_FILE` into account by default. I need to investigate it

**Comment by mk-5** [comment]
okay mhmm .. it looks that it needs to be handled manually. I checked a few libs, this is what I found: https://github.com/minio/minio-go/blob/master/transport.go

**Comment by izifortune** [comment]
The env variable check `SSL_CERT_FILE` looks perfect as majority of the people that uses custom certs will already have this provided.

Happy to help out on the testing side. Sorry but go is not my cup of tea

**Comment by mk-5** [comment]
@izifortune pls check the latest version 1.1.0

**Comment by izifortune** [comment]
Working perfectly now thanks @mk-5

**Comment by mk-5** [comment]
awesome :)
